version: "3.9"
services:
  ticketing-next-db:
    image: postgres
    restart: always
    container_name: ticketing-next-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ticketing-next
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: